Added two service
RocketChat/Rocket.Chat.PWA pull request #21
Opened 2017-06-19 17:12 UTC by InsaneNaman

Function for custom emoji , user roles , Logout, login using localstorage

2017-06-20 18:42 UTC, ggazzo requested changes
Use an abstraction to reuse the send methods and avoid mistakes, you should generate a random id for each command sent and use the same connection for all services

2017-06-20 18:42 UTC, ggazzo commented on src/app/shared/REALtime API/auth/auth.service.ts
> +    ping.subscribe(() => this.subject$.next('pong'));
the correct is send :  `this.subject$.next(JSON.stringify({msg:"pong"}))`

2017-06-22 13:49 UTC, InsaneNaman commented on src/app/shared/REALtime API/auth/auth.service.ts
> +    ping.subscribe(() => this.subject$.next('pong'));
Okay 😄  Just give me some time, I'll do the changes

2017-06-22 14:39 UTC, danielszenasi commented on src/app/shared/REALtime API/auth/auth.service.ts
> +    ping.subscribe(() => this.subject$.next('pong'));
https://github.com/RocketChat/Rocket.Chat.PWA/pull/23
Here is my suggestion for this problem

2017-06-22 14:46 UTC, InsaneNaman commented on src/app/shared/REALtime API/auth/auth.service.ts
> +    ping.subscribe(() => this.subject$.next('pong'));
I know , daniel buddy you have opened a PR. I am working on the same or i can say we(me and @inf3cti0n95 ) also have found solution. Just give me some time , tomorrow or day after tomorrow we(you and me) will together merge our solution. Please, i just want some. 😄

2017-07-03 16:32 UTC, InsaneNaman commented
- [ ] Connection(rxjs realtime package)

- [ ]  Request / Response Methods(rxjs realtime package)

- [ ] Subscriptions (rxjs realtime Package)

- [ ]  Apply UI system (Angular Material, Teradata Covalent(3rd party)) 

- [ ]  User login/registration 

- [ ] List channels

2017-07-12 11:42 UTC, InsaneNaman commented
![image](https://user-images.githubusercontent.com/13780776/28116102-2fb4090c-6725-11e7-8f40-8bf0cfbb9d70.png)
![image](https://user-images.githubusercontent.com/13780776/28116111-3e00b488-6725-11e7-8b89-d2913a975fcf.png)

![image](https://user-images.githubusercontent.com/13780776/28116127-4b607672-6725-11e7-9662-bca329e8bedf.png)

2017-07-14 05:15 UTC, InsaneNaman commented
**Side Nav remaining**

![image](https://user-images.githubusercontent.com/13780776/28199194-7939131c-6881-11e7-8c56-3953c8c094fb.png)
![image](https://user-images.githubusercontent.com/13780776/28199201-8726ec9c-6881-11e7-9482-96b1d14f97f5.png)

2017-08-21 18:58 UTC, closed without merging